### PR TITLE
Update events.md

### PR DESCRIPTION
**Pull request by diskoflorian**
Adapt documentation with bolt last version

### CODE REVIEW

**Comment by SahAssar** [comment]
It would be good to also include the use statement for `EventDispatcherInterface` :)

**Comment by bobdenotter** [comment]
@diskoflorian Can you update this PR to include the `use` statement?

**Comment by diskoflorian** [comment]
@bobdenotter Done :)

**Comment by bobdenotter** [comment]
Thanks, @diskoflorian. Merging in! 👍

**Pull request merged**
