### PR TITLE
Exclude handled attributes from the general list in form_start

### LINKED ISSUE #269: In first line of a Bolt form, there is a duplicate 'name='
I'm using the newest version of Boltforms. I noticed in the first line of code of the form, the name attribute is mentioned twice. What is the purpose of that? According to a html validator, it is an error and I want to remove it. What file do I need to edit for this?

### PR DESCRIPTION
**Pull request by rossriley**
Fixes #269

Excludes the attributes that are already managed from the general attributes list.

### CODE REVIEW

**Comment by jadwigo** [comment]
Even better!

**Comment by jadwigo** [comment]
@rossriley can you tag a new release?

**Comment by mborn319** [comment]
Thanks @rossriley !

**Comment by rossriley** [comment]
New release tagged, 4.2.5.

**Pull request merged**
