### PR TITLE
date format 'c' is not compatible with sql

### PR DESCRIPTION
**Pull request by jadwigo**
I prefer 'Y-m-d H:i:s' because that's the format a sql database likes.

I don't yet know if this has side effects

### CODE REVIEW

**Comment by bobdenotter** [comment]
@rossriley Any comments? I bumped into the same issue, and this seems to fix it for me?

**Comment by GawainLynch** [comment]
That was very deliberately an ISO 8601 date, which isn't unpredictable.

**Comment by jadwigo** [comment]
that was me using imprecise wording - the date format was predictable but because the database inserts were triggering exceptions this was a problem

**Comment by GawainLynch** [comment]
Haha … You've taken the Gawain Advanced Course in Miscommunication then I see.

This is part of the reason I split all this out too btw, the transformed values shouldn't be going to the database, but should be going to Twig and that is where the ISO 8601 date became important.

In 3.x/4.x/master you probably want to look at the handler itself

**Pull request merged**
